ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDAUDMipCJhuAh9NbwI+yGGMVH0MsJCnxDk3BrVTRPh5cMscJXzJZuutzWO8kezZSMIBHRggLhskQPp0uvI3U9mL7qOges8CIXKsl5GIUHAMMc3nvlP1BDvuYQCWQoMVz67JhjUVxOGsTpJGtQn5srsTq5LqLAbuA41NWVnW24Dv9RjGcekeN1MtnZALcPZo1TcIEGaoLufjJ6F0/mfQWE2r1SxjM+YgKmhgmE2g8CAbkReVkfyME2CGn+S9SGFMr5gIhm/fBxI+Ssdc5AtolDPPbsoyEu0HuezBc8/yJ+kyyve1UGjysKk9RMzLq9XoXOOWG4Lcqaz1xxldcKkwLJsPFCm7floAokgN/4rn6g5aj5slu7EJ7Nis/tSx7KXTlfWbZFnqbVm7vSBhl+muz8jXipy+7HpYu1WjYfy9GaTebePqCNtNvtDpLOih12XrXl56Lsyjz9b9B9KeYmhmatXDhC9qSkK+2mW3aTrNpJY/zgAPVCEZwj8UgNRqNJ7d5M= dreamshao
version: 2
jobs:
  build:
    docker:
      - image: felicianotech/docker-hugo:0.27.1
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Build Our Statically Generated Docs Website with Hugo"
          command: HUGO_ENV=production hugo -v -s src/
      - persist_to_workspace:
          root: /root/project
          paths:src/public/
  html-testing:
    docker:
      - image: felicianotech/docker-hugo:0.27.1
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: /root/project
      - run:
          name: "Test With HTML Proofer"
          command: echo "This is where we'd do testing with HTML Proofer."
  ui-testing:
    docker:
      - image: felicianotech/docker-hugo:0.27.1
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: /root/project
      - run:
          name: "Test With Selenium or Behat"
          command: echo "This is where we'd run a headless browser and test our site's UI."
  process-testing:
    docker:
      - image: felicianotech/docker-hugo:0.27.1
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: /root/project
      - run:
          name: "Test the commit for org or team processes"
          command: |
            echo "This is where we'd test this commit for things our project wants to enforce"
            echo " such as code formatting, the signing of a CLA, security requirements, etc."
  deploy:
    docker:
      - image: felicianotech/docker-hugo:0.27.1
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: /root/project
      - run:
          name: "Deploy Our Docs Site"
          command: echo "This is where we'd deploy using rsync, awscli, etc."
# Below would be the Workflows specifc config, which we're leaving off for brevity (this example as already lengthy.
